### ISSUE TITLE
lldpd service error

### ISSUE THREAD

**Issue by liyang-qianxin** [jsimonetti/lldpd#1]
[root@localhost lldpd-1.0.5]# systemctl status lldpd.service ● lldpd.service - LLDP daemon    Loaded: loaded (/usr/lib/systemd/system/lldpd.service; disabled; vendor preset: disabled)    Active: inactive (dead)      Docs: man:lldpd(8)  Mar 31 03:39:02 localhost.localdomain systemd[1]: [/usr/lib/systemd/system/lldpd.service:16] Unknown lvalue 'ProtectKernelTunables' in section 'Service' Mar 31 03:39:02 localhost.localdomain systemd[1]: [/usr/lib/systemd/system/lldpd.service:17] Unknown lvalue 'ProtectControlGroups' in section 'Service' Mar 31 03:39:02 localhost.localdomain systemd[1]: [/usr/lib/systemd/system/lldpd.service:18] Unknown lvalue 'ProtectKernelModules' in section 'Service' [root@localhost lldpd-1.0.5]# systemctl start lldpd.service Job for lldpd.service failed because the control process exited with error code. See "systemctl status lldpd.service" and "journalctl -xe" for details.

**Comment by jsimonetti** [comment]
This is a systemd issue and not related to lldpd.
I would suggest asking this to the maintainer of your lldpd package.
